{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "collectserver.fullname" . }}
spec:
  hosts:
  - {{ .Values.gatewayServers.hosts }}
  gateways:
  - {{ .Release.Name }}-gw
  http:
  - name: "reviews-v2-routes"
    match:
    - uri:
        prefix: {{ .Values.virtualService.context }}/
    rewrite:
      uri: {{ .Values.virtualService.context }}/
    route:
    - destination:
        host: {{ include "collectserver.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
{{- end }}
